import java.net.URI

plugins {
    alias(libs.plugins.kotlin.multiplatform)
    id("kobweb-compose")
    id("com.varabyte.kobweb.internal.publish")
}

group = "com.varabyte.kobwebx"
version = libs.versions.kobweb.get()

private val GENERATED_SRC_ROOT = "build/generated/icons/src/jsMain/kotlin"

// Pinned commit of google/material-design-icons. Bump together with the `fetchMsIcons` task output.
private val MS_SOURCE_COMMIT = "229d4d6de51043272fdbb0137652f18f5ff4034b"
private val MS_VARIABLEFONT_URL_BASE =
    "https://raw.githubusercontent.com/google/material-design-icons/$MS_SOURCE_COMMIT/variablefont"

// URL-encoded axis suffix: [FILL,GRAD,opsz,wght]
private val MS_AXIS_SUFFIX = "%5BFILL%2CGRAD%2Copsz%2Cwght%5D"

enum class IconStyle {
    OUTLINED,
    ROUNDED,
    SHARP;
}

val fetchMsIconsTask = tasks.register("fetchMsIcons") {
    val outputFile = layout.projectDirectory.file("ms-icon-list.txt")
    val sourceCommit = MS_SOURCE_COMMIT
    val urlBase = MS_VARIABLEFONT_URL_BASE
    val axisSuffix = MS_AXIS_SUFFIX

    doLast {
        val families = listOf(
            "mso" to "MaterialSymbolsOutlined",
            "msr" to "MaterialSymbolsRounded",
            "mss" to "MaterialSymbolsSharp",
        )

        outputFile.asFile.bufferedWriter().use { writer ->
            writer.appendLine("# See the README.md for more information about this file. It is parsed by this project's generateIcons gradle task.")
            writer.appendLine("# Generated by the fetchMsIcons task from google/material-design-icons @ $sourceCommit")

            for ((prefix, family) in families) {
                val url = "$urlBase/$family$axisSuffix.codepoints"
                println("Fetching $url")
                val connection = URI(url).toURL().openConnection()
                connection.setRequestProperty("User-Agent", "kobweb-silk-icons-ms-generator")
                val text = connection.getInputStream().use { it.readBytes().decodeToString() }

                val names = text.lineSequence()
                    .filter { it.isNotBlank() }
                    .map { it.substringBefore(' ') }
                    .toList()

                if (names.isEmpty()) throw GradleException("No icon codepoints parsed for $family")
                writer.appendLine("$prefix=${names.joinToString(",")}")
            }
        }
        println("Wrote ${outputFile.asFile.absolutePath}")
    }
}

val generateIconsTask = tasks.register("generateIcons") {
    val srcFile = layout.projectDirectory.file("ms-icon-list.txt")
    val dstFile =
        layout.projectDirectory.file("$GENERATED_SRC_ROOT/com/varabyte/kobweb/silk/components/icons/ms/MsIcons.kt")

    inputs.files(srcFile)
    outputs.dir(GENERATED_SRC_ROOT)

    doLast {
        val iconRawNames = srcFile.asFile
            .readLines()
            .asSequence()
            .filter { line -> !line.startsWith("#") && line.isNotBlank() }
            .associate { line ->
                // Convert icon name to function name, e.g.
                // home -> MsHome, arrow_back -> MsArrowBack
                line.split("=", limit = 2).let { parts ->
                    val style = when (parts[0]) {
                        "mso" -> IconStyle.OUTLINED
                        "msr" -> IconStyle.ROUNDED
                        "mss" -> IconStyle.SHARP
                        else -> throw GradleException("Unexpected style grouping: ${parts[0]}")
                    }
                    val names = parts[1]

                    style to names.split(",")
                }
            }

        // For each icon name, figure out what categories they are in. This will affect the function signature we generate.
        val iconStyleGroups = mutableMapOf<String, MutableSet<IconStyle>>()
        iconRawNames.forEach { entry ->
            val category = entry.key
            entry.value.forEach { rawName ->
                iconStyleGroups.computeIfAbsent(rawName) { mutableSetOf() }.add(category)
            }
        }

        val iconMethodEntries = iconStyleGroups
            .map { entry ->
                val rawName = entry.key

                @Suppress("DEPRECATION") // capitalize is way more readable than a direct replacement
                val methodName = "Ms" + rawName.split("_").joinToString("") { it.capitalize() }
                val styles = entry.value

                when {
                    // A rare solo-style icon? No need to allow a user to pass in a style parameter in that case
                    styles.size == 1 -> {
                        "@Composable fun $methodName(modifier: Modifier = Modifier) = MsIcon(\"$rawName\", modifier, ${styles.first().name})"
                    }

                    styles.isEmpty() -> {
                        // This shouldn't be possible, but just in case...
                        throw GradleException("Unexpected icon entry with no styles: $entry")
                    }

                    styles.size == IconStyle.values().size -> {
                        // This icon supports all styles. No need to assert input parameters.
                        "@Composable fun $methodName(modifier: Modifier = Modifier, style: MsIconStyle = OUTLINED) = MsIcon(\"$rawName\", modifier, style)"
                    }

                    else -> {
                        // Not all styles are valid. For now, we throw an exception to inform the user about this, but we
                        // can always decide to relax this later.
                        "@Composable fun $methodName(modifier: Modifier = Modifier, style: MsIconStyle = ${styles.first().name}) = MsIcon(\"$rawName\", modifier, style.also { it.assertValidStyle(\"$methodName\", ${styles.joinToString { it.name }}) })"
                    }
                }
            }

        val iconsCode =
            """
            |//@formatter:off
            |@file:Suppress("unused", "SpellCheckingInspection")
            |
            |// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
            |// THIS FILE IS AUTOGENERATED.
            |//
            |// Do not edit this file by hand. Instead, update `ms-icon-list.txt` in the module root (via the
            |// `fetchMsIcons` Gradle task) and run the Gradle task "generateIcons".
            |// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
            |
            |package com.varabyte.kobweb.silk.components.icons.ms
            |
            |import androidx.compose.runtime.*
            |import com.varabyte.kobweb.compose.ui.Modifier
            |import com.varabyte.kobweb.compose.ui.toAttrs
            |import com.varabyte.kobweb.silk.components.icons.ms.MsIconStyle.OUTLINED
            |import com.varabyte.kobweb.silk.components.icons.ms.MsIconStyle.ROUNDED
            |import com.varabyte.kobweb.silk.components.icons.ms.MsIconStyle.SHARP
            |import org.jetbrains.compose.web.dom.Span
            |import org.jetbrains.compose.web.dom.Text
            |
            |enum class MsIconStyle {
            |    OUTLINED,
            |    ROUNDED,
            |    SHARP;
            |}
            |
            |private fun MsIconStyle.toClassNameSuffix(): String {
            |    return when (this) {
            |        OUTLINED -> "-outlined"
            |        ROUNDED -> "-rounded"
            |        SHARP -> "-sharp"
            |    }
            |}
            |
            |private fun MsIconStyle.assertValidStyle(methodName: String, vararg validStyles: MsIconStyle) {
            |    if (this !in validStyles) {
            |        error("Attempted to render \"${'$'}methodName\" with style ${'$'}this. Must be one of: ${'$'}{validStyles.joinToString()}")
            |    }
            |}
            |
            |@Composable
            |fun MsIcon(
            |    name: String,
            |    modifier: Modifier,
            |    style: MsIconStyle = OUTLINED,
            |) {
            |    Span(
            |        attrs = modifier.toAttrs { classes("material-symbols${'$'}{style.toClassNameSuffix()}") }
            |    ) {
            |        Text(name)
            |    }
            |}
            |
            |${iconMethodEntries.joinToString("\n")}
            """.trimMargin()

        dstFile.asFile.apply {
            parentFile.mkdirs()
            writeText(iconsCode)
        }
    }
}

kotlin {
    js {
        browser()
    }

    sourceSets {
        jsMain {
            kotlin.srcDir(generateIconsTask)
            dependencies {
                implementation(libs.compose.runtime)
                implementation(libs.compose.html.core)

                api(projects.frontend.kobwebCompose)
            }
        }
    }
}

kobwebPublication {
    artifactName.set("Kobweb Silk Icons (Material Symbols)")
    artifactId.set("silk-icons-ms")
    description.set("A collection of composables that directly wrap Google Material Symbols.")
}
