import java.net.URI

plugins {
    alias(libs.plugins.kotlin.multiplatform)
    id("kobweb-compose")
    id("com.varabyte.kobweb.internal.publish")
}

group = "com.varabyte.kobwebx"
version = libs.versions.kobweb.get()

val ICON_LIST_FILE_NAME = "ms-icon-list.txt"

enum class IconStyle {
    OUTLINED,
    ROUNDED,
    SHARP;
}

@CacheableTask
abstract class FetchIconsTask : DefaultTask() {
    @get:Input
    abstract val sourceCommit: Property<String>

    @get:OutputFile
    abstract val iconsFile: RegularFileProperty

    private val families = mapOf(
        "mso" to "MaterialSymbolsOutlined",
        "msr" to "MaterialSymbolsRounded",
        "mss" to "MaterialSymbolsSharp",
    )

    // URL-encoded axis suffix: [FILL,GRAD,opsz,wght]
    private val MS_AXIS_SUFFIX = "%5BFILL%2CGRAD%2Copsz%2Cwght%5D"

    @TaskAction
    fun fetch() {
        val sourceCommit = sourceCommit.get()
        val urlBase = "https://raw.githubusercontent.com/google/material-design-icons/$sourceCommit/variablefont"

        val iconsFile = iconsFile.get().asFile
        iconsFile.bufferedWriter().use { writer ->
            writer.appendLine("# See the README.md for more information about this file. It is parsed by this project's generateIcons gradle task.")
            writer.appendLine("# Generated by the fetchMsIcons task from google/material-design-icons @ $sourceCommit")

            for ((prefix, family) in families) {
                val url = "$urlBase/$family$MS_AXIS_SUFFIX.codepoints"
                logger.lifecycle("Fetching $url")
                val connection = URI(url).toURL().openConnection()
                connection.setRequestProperty("User-Agent", "kobweb-silk-icons-ms-generator")
                val text = connection.getInputStream().use { it.readBytes().decodeToString() }

                val names = text.lineSequence()
                    .filter { it.isNotBlank() }
                    .map { it.substringBefore(' ') }
                    .toList()

                if (names.isEmpty()) throw GradleException("No icon codepoints parsed for $family")
                writer.appendLine("$prefix=${names.joinToString(",")}")
            }
        }
        logger.lifecycle("Wrote ${iconsFile.absolutePath}")
    }
}

val fetchMsIconsTask = tasks.register<FetchIconsTask>("fetchIcons") {
    group = "Icon"
    description = "Download information that lets us create $ICON_LIST_FILE_NAME, which is used to generate icons."

    sourceCommit.set("229d4d6de51043272fdbb0137652f18f5ff4034b")
    iconsFile.set(layout.projectDirectory.file(ICON_LIST_FILE_NAME))
}

@CacheableTask
abstract class GenerateIconsTask : DefaultTask() {
    @get:InputFile
    @get:PathSensitive(PathSensitivity.NONE)
    abstract val srcFile: RegularFileProperty

    @get:OutputDirectory
    abstract val genSrcRoot: DirectoryProperty

    @TaskAction
    fun generate() {
        val iconRawNames = srcFile.get().asFile
            .readLines()
            .asSequence()
            .filter { line -> !line.startsWith("#") && line.isNotBlank() }
            .associate { line ->
                // Convert icon name to function name, e.g.
                // home -> MsHome, arrow_back -> MsArrowBack
                line.split("=", limit = 2).let { parts ->
                    val style = when (parts[0]) {
                        "mso" -> IconStyle.OUTLINED
                        "msr" -> IconStyle.ROUNDED
                        "mss" -> IconStyle.SHARP
                        else -> throw GradleException("Unexpected style grouping: ${parts[0]}")
                    }
                    val names = parts[1]

                    style to names
                        .split(",")
                        // Each icon gets written to its own file, so to prevent file name collisions from ever happening,
                        // normalize each name to its version without underscores (since those get removed later) and keep
                        // only the longest version (e.g. "print_shop" would win out over "printshop".
                        .groupBy { it.replace("_", "") }
                        .map { (_, values) -> values.maxBy { it.length } }
                        .toList()
                }
            }

        // For each icon name, figure out what categories they are in. This will affect the function signature we generate.
        val iconStyleGroups = mutableMapOf<String, MutableSet<IconStyle>>()
        iconRawNames.forEach { entry ->
            val category = entry.key
            entry.value.forEach { rawName ->
                iconStyleGroups.computeIfAbsent(rawName) { mutableSetOf() }.add(category)
            }
        }

        val iconMethodEntries = iconStyleGroups
            .map { entry ->
                val rawName = entry.key

                @Suppress("DEPRECATION") // capitalize is way more readable than a direct replacement
                val methodName = "Ms" + rawName.split("_").joinToString("") { it.capitalize() }
                val styles = entry.value

                methodName to when {
                    // A rare solo-style icon? No need to allow a user to pass in a style parameter in that case
                    styles.size == 1 -> {
                        "@Composable fun $methodName(modifier: Modifier = Modifier) = MsIcon(\"$rawName\", modifier, ${styles.first().name})"
                    }

                    styles.isEmpty() -> {
                        // This shouldn't be possible, but just in case...
                        throw GradleException("Unexpected icon entry with no styles: $entry")
                    }

                    styles.size == IconStyle.entries.size -> {
                        // This icon supports all styles. No need to assert input parameters.
                        "@Composable fun $methodName(modifier: Modifier = Modifier, style: MsIconStyle = OUTLINED) = MsIcon(\"$rawName\", modifier, style)"
                    }

                    else -> {
                        // Not all styles are valid. For now, we throw a runtime exception (via assertValidStyle) to
                        // inform the user about this, but we can always decide to relax this later.
                        "@Composable fun $methodName(modifier: Modifier = Modifier, style: MsIconStyle = ${styles.first().name}) = MsIcon(\"$rawName\", modifier, style.also { it.assertValidStyle(\"$methodName\", ${styles.joinToString { it.name }}) })"
                    }
                }
            }.toMap()

        val iconsHeader =
            """
            |//@formatter:off
            |@file:Suppress("unused", "SpellCheckingInspection")
            |
            |// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
            |// THIS FILE IS AUTOGENERATED.
            |//
            |// Do not edit this file by hand. Instead, update `ms-icon-list.txt` in the module root (via the
            |// `fetchMsIcons` Gradle task) and run the Gradle task "generateIcons".
            |// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
            |
            |package com.varabyte.kobweb.silk.components.icons.ms
            |
            |import androidx.compose.runtime.*
            |import com.varabyte.kobweb.compose.ui.Modifier
            |import com.varabyte.kobweb.silk.components.icons.ms.MsIconStyle.*
            |
            """.trimMargin()

        val dstDir = genSrcRoot.dir("com/varabyte/kobweb/silk/components/icons/ms").get().asFile
        dstDir.mkdirs()

        with(dstDir.resolve("_MsIcon.kt")) {
            writeText(iconsHeader)
            appendText(
                $$"""
                |import com.varabyte.kobweb.compose.ui.toAttrs
                |import org.jetbrains.compose.web.dom.Span
                |import org.jetbrains.compose.web.dom.Text
                |
                |enum class MsIconStyle {
                |    OUTLINED,
                |    ROUNDED,
                |    SHARP;
                |}
                |
                |private fun MsIconStyle.toClassNameSuffix(): String {
                |    return when (this) {
                |        OUTLINED -> "-outlined"
                |        ROUNDED -> "-rounded"
                |        SHARP -> "-sharp"
                |    }
                |}
                |
                |private fun MsIconStyle.assertValidStyle(methodName: String, vararg validStyles: MsIconStyle) {
                |    if (this !in validStyles) {
                |        error("Attempted to render \"$methodName\" with style $this. Must be one of: ${validStyles.joinToString()}")
                |    }
                |}
                |
                |@Composable
                |fun MsIcon(
                |    name: String,
                |    modifier: Modifier,
                |    style: MsIconStyle = OUTLINED,
                |) {
                |    Span(
                |        attrs = modifier.toAttrs { classes("material-symbols${style.toClassNameSuffix()}") }
                |    ) {
                |        Text(name)
                |    }
                |}
                |
                """.trimMargin()
            )
        }

        iconMethodEntries.forEach { (methodName, iconCode) ->
            with(dstDir.resolve("$methodName.kt")) {
                writeText(iconsHeader)
                appendText("\n")
                appendText(iconCode)
            }
        }

        logger.info("Generated ${iconMethodEntries.size} icon files")
    }
}
val generateIconsTask = tasks.register<GenerateIconsTask>("generateIcons") {
    group = "Icon"
    description = "Generate Kotlin bindings for Material Symbols."
    srcFile.set(layout.projectDirectory.file(ICON_LIST_FILE_NAME))
    genSrcRoot.set(layout.projectDirectory.dir("build/generated/icons/src/jsMain/kotlin"))
}

kotlin {
    js {
        browser()
    }

    sourceSets {
        jsMain {
            kotlin.srcDir(generateIconsTask)
            dependencies {
                implementation(libs.compose.runtime)
                implementation(libs.compose.html.core)

                api(projects.frontend.kobwebCompose)
            }
        }
    }
}

kobwebPublication {
    artifactName.set("Kobweb Silk Icons (Material Symbols)")
    artifactId.set("silk-icons-ms")
    description.set("A collection of composables that directly wrap Google Material Symbols.")
}
