import java.util.Locale

plugins {
    alias(libs.plugins.kotlin.multiplatform)
    id("kobweb-compose")
    id("com.varabyte.kobweb.internal.publish")
}

group = "com.varabyte.kobwebx"
version = libs.versions.kobweb.get()

private val GENERATED_SRC_ROOT = "build/generated/icons/src/jsMain/kotlin"

val generateIconsTask = tasks.register("generateIcons") {
    val srcFile = layout.projectDirectory.file("lucide-icon-list.txt")
    val dstFile =
        layout.projectDirectory.file("$GENERATED_SRC_ROOT/com/varabyte/kobweb/silk/components/icons/lucide/LucideIcons.kt")

    inputs.files(srcFile)
    outputs.dir(GENERATED_SRC_ROOT)

    doLast {
        val lines = srcFile.asFile
            .readLines()
            .filter { line -> line.isNotBlank() && !line.startsWith("#") }

        // Parse the version from the comment header, e.g. "# Lucide icon list — version 0.574.0"
        val lucideVersion = srcFile.asFile.readLines()
            .firstOrNull { it.startsWith("# Lucide icon list") }
            ?.substringAfter("version ", "")
            ?.trim()
            ?.ifEmpty { null }

        // Parse active icons: "lucide=icon1,icon2,..."
        val activeIcons = lines
            .firstOrNull { it.startsWith("lucide=") }
            ?.removePrefix("lucide=")
            ?.split(",")
            ?.filter { it.isNotBlank() }
            ?: emptyList()

        // Parse deprecated icons: "deprecated=icon1>canonical1,icon2>canonical2,..."
        // Each entry is "deprecatedName>canonicalName"
        val deprecatedIcons: Map<String, String> = lines
            .firstOrNull { it.startsWith("deprecated=") }
            ?.removePrefix("deprecated=")
            ?.split(",")
            ?.filter { it.isNotBlank() }
            ?.associate { entry ->
                val parts = entry.split(">", limit = 2)
                if (parts.size != 2) throw GradleException("Invalid deprecated entry: $entry")
                parts[0] to parts[1]
            }
            ?: emptyMap()

        fun rawNameToMethodName(rawName: String) = "Lucide" + rawName.split("-").joinToString("") {
            it.replaceFirstChar {
                if (it.isLowerCase()) it.titlecase() else it.toString()
            }
        }

        val activeMethodEntries = activeIcons.map { rawName ->
            val methodName = rawNameToMethodName(rawName)
            "@Composable fun $methodName(modifier: Modifier = Modifier) = LucideIcon(\"$rawName\", modifier)"
        }

        val activeMethodNames = activeIcons.map { rawNameToMethodName(it) }.toSet()

        val deprecatedMethodEntries = deprecatedIcons.entries
            .sortedBy { it.key }
            .mapNotNull { (deprecatedName, canonicalName) ->
                val deprecatedMethodName = rawNameToMethodName(deprecatedName)
                // Skip if the deprecated method name collides with an active icon's method name
                if (deprecatedMethodName in activeMethodNames) return@mapNotNull null
                val canonicalMethodName = rawNameToMethodName(canonicalName)
                "@Deprecated(\"Use $canonicalMethodName instead.\", ReplaceWith(\"$canonicalMethodName(modifier)\"))\n@Composable fun $deprecatedMethodName(modifier: Modifier = Modifier) = LucideIcon(\"$canonicalName\", modifier)"
            }

        val activeIconsBlock = buildString {
            append(activeMethodEntries.joinToString("\n"))
        }

        val deprecatedBlock = if (deprecatedMethodEntries.isNotEmpty()) {
            "\n// Deprecated icon aliases\n" + deprecatedMethodEntries.joinToString("\n")
        } else {
            ""
        }

        val iconsCode =
            """
            |//@formatter:off
            |@file:Suppress("unused", "SpellCheckingInspection")
            |
            |// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
            |// THIS FILE IS AUTOGENERATED.
            |//
            |// Do not edit this file by hand. Instead, update `lucide-icon-list.txt` in the module root and run the
            |// Gradle task "generateIcons"
            |// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
            |
            |package com.varabyte.kobweb.silk.components.icons.lucide
            |
            |import androidx.compose.runtime.*
            |import com.varabyte.kobweb.compose.ui.Modifier
            |import com.varabyte.kobweb.compose.ui.toAttrs
            |import org.jetbrains.compose.web.dom.I
            |
            |/**
            | * Renders a Lucide icon using the `<i data-lucide="name">` convention.
            | *
            | * Requires the Lucide JavaScript library to be loaded on the page, e.g. via CDN:
            | * ```html
            | * <script src="https://unpkg.com/lucide@latest"></script>
            | * <script>lucide.createIcons();</script>
            | * ```
            | * Version ${lucideVersion ?: "unknown"} is recommended.
            | *
            | * See also: https://lucide.dev/
            | */
            |@Composable
            |fun LucideIcon(
            |    name: String,
            |    modifier: Modifier = Modifier,
            |) {
            |    I(
            |        attrs = modifier.toAttrs {
            |            attr("data-lucide", name)
            |        }
            |    )
            |}
            |
            |$activeIconsBlock$deprecatedBlock
            """.trimMargin()

        dstFile.asFile.apply {
            parentFile.mkdirs()
            writeText(iconsCode)
        }
    }
}

kotlin {
    js {
        browser()
    }

    sourceSets {
        jsMain {
            kotlin.srcDir(generateIconsTask)
            dependencies {
                implementation(libs.compose.runtime)
                implementation(libs.compose.html.core)

                api(projects.frontend.kobwebCompose)
            }
        }
    }
}

kobwebPublication {
    artifactName.set("Kobweb Silk Icons (Lucide)")
    artifactId.set("silk-icons-lucide")
    description.set("A collection of composables that directly wrap Lucide icons.")
}
