name: Build & Test

on:
  # starting with a minimal scope; potentially we can set this to '*' but we can decide if that's helper later
  push:
    branches: [ 'dev' ]
  pull_request:
    branches: [ '*' ]

env:
  GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx4g"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build & Test
        run: ./gradlew build --stacktrace
